apiVersion: apps/v1
kind: Deployment

metadata:
  name: myapp

spec: 
  selector: 
    matchLabels:
      app: my-web-app
  replicas: 3
  template:  
    metadata:
      name: my-web-app
      labels:
        app: my-web-app
    spec:
      containers:
      - name: custom-image
      
        image: ayaabdelsamed/nginx-test
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
